Do away with slices
The previous commit didn't compile because of ...

```
./main.go:8:26: cannot use proxy (type *proxy.Proxy) as type consumer.proxy in argument to consumer.New:
        *proxy.Proxy does not implement consumer.proxy (wrong type for GetResources method)
                have GetResources() ([]*resource.Resource, error)
                want GetResources() ([]consumer.resource, error)
```

Which I thought happened because the return values there were slices
with compatible but different types.

But it turns out that getting rid of slices doesn't really solve the
problem:

```
./main.go:8:26: cannot use proxy (type *proxy.Proxy) as type consumer.proxy in argument to consumer.New:
        *proxy.Proxy does not implement consumer.proxy (wrong type for GetResources method)
                have GetResources() (*resourcelist.ResourceList, error)
                want GetResources() (consumer.resourceList, error)
```